//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trial2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_offer
    {
        public decimal Product_id { get; set; }
        public string Product_title { get; set; }
        public string Product_desc { get; set; }
        public string Product_image { get; set; }
    }
}
